# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVlsJLZB9nDRUEsd_viDOvqjmtKwPwxp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("headbrain.csv")
df
df.shape
df.head()

x = df['Head Size(cm^3)'].values
y = df['Brain Weight(grams)'].values

plt.figure(figsize=(10,6))
plt.scatter(x,y)
plt.show()

# Mean values
mean_x = np.mean(x)
mean_y = np.mean(y)

# Linear regression (from scratch)
numer = 0
denom = 0
n = len(x)

for i in range(n):
    numer += (y[i] - mean_y) * (x[i] - mean_x)
    denom += (x[i] - mean_x) ** 2

slope = numer / denom
intercept = mean_y - (slope * mean_x)

print("Slope:", slope)
print("Intercept:", intercept)

#predicted values

predictions = []
for i in range(n):
  y_pred= slope * x[i] + intercept
  predictions.append(int(y_pred))

print(predictions[:5])

#actual values
print(y[:5])

plt.figure(figsize=(10,6))
plt.scatter(x,y)
plt.plot(x,predictions,color='red')
plt.show()

#mse mean sq error
error = 0
for i in range(n):
  error+= (predictions[i] - y[i])**2

mse=error/n
print("Mse:",mse)

#mse
np.sqrt(mse)

# Normalization
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

x.shape

x = np.reshape(x, (-1,1))
y = np.reshape(y, (-1,1))

minmax = MinMaxScaler()
scale_x = minmax.fit_transform(x)
scale_y = minmax.fit_transform(y)

print(scale_x[:5])

def gradientDescent(epochs,alpha):
  slope, inter =0,0
  for i in range(epochs):
    y_pred = slope * scale_x + inter # y = mx +c
    loss = y_pred - scale_y
    gradSlope = (2/n) * np.dot(loss.T, scale_x)
    gradInter = (2/n) * np.sum(loss)
    slope = slope - gradSlope * alpha
    inter = inter - gradInter * alpha
  return slope, inter

epochs = 100
alpha = 0.01
slope , inter = gradientDescent(epochs,alpha)

print(slope)
print(inter)

predictions = []
for i in range(n):
  y_pred= slope[0][0] * scale_x[i] + inter
  predictions.append(y_pred)

plt.figure(figsize=(10,6))
plt.scatter(scale_x,scale_y)
plt.plot(scale_x,predictions,color='red')
plt.show()